### PR TITLE
Add extended chat/command functionality

### PR DESCRIPTION
**Pull request by zavdav**
Since fundamentals is supposed to replace essentials SoonTM, i have decided to start adding some of essentials' functionality regarding chat/commands into fundamentals. 
(Will hopefully be updating this pr regularly)

### CODE REVIEW

**Comment by zavdav** [comment]
^ With these commits, i've made it so fundamentals uses its permissions hook to display a users' group prefix before their name in public chat and in afk status messages.

**Comment by zavdav** [comment]
^ Added /mute functionality with the option to mute permanently or specify a duration to mute temporarily. Durations are also formatted

**Comment by zavdav** [comment]
^ Added /ignore functionality

**Comment by zavdav** [comment]
Added /msg and /r commands

**Comment by zavdav** [comment]
^ Added /realname

**Comment by zavdav** [comment]
^ Added /seen

**Comment by zavdav** [comment]
^ Added /broadcast

**Comment by svgaming234** [comment]
^ Added /weather with support for changing weather in a specified world

**Comment by zavdav** [comment]
^ Added /list with the option to sort players by their group

**Pull request closed without merging**
