### PR TITLE
Add better home list with the /homes command (with zavdav)

### PR DESCRIPTION
**Pull request by svgaming234**
Feature by zavdav and SvGaming234

### CODE REVIEW

**Comment by RhysB** [comment]
Please resolve conflict when possible

**Comment by svgaming234** [comment]
@RhysB Conflict resolved

**Comment by RhysB** [comment]
Just doing some testing, let me know @svgaming234 if you can merge after @Grassboii or @zavdav has reviewed this.

Hoping to allow you guys to merge without my involvement.

**Review by zavdav — APPROVED** [review]
@svgaming234 you don't actually need to pass an instance of Fundamentals to CommandHomes since you're using getInstance() for everything. other than that, everything looks good to me

**Review by Grassboii — APPROVED** [review]

**Comment by svgaming234** [comment]
@RhysB Still cannot merge, still says only people with write access to the repo can merge
image

**Comment by svgaming234** [comment]
oh i can merge it now, i forgot to accept the invite to the org @RhysB

**Pull request merged**
